FROM centos
MAINTAINER  QMJQ 20180927 http://www.opsxyz.com
RUN rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN localedef -c -f UTF-8 -i zh_CN zh_CN.utf8
COPY jdk-8u151-linux-x64.tar.gz /usr/local/jdk/jdk-8u151-linux-x64.tar.gz
WORKDIR /usr/local/jdk
RUN tar -zxvf jdk-8u151-linux-x64.tar.gz  && rm -rf jdk-8u151-linux-x64.tar.gz
ENV LC_ALL zh_CN.utf8
ENV JAVA_HOME /usr/local/jdk/jdk1.8.0_151
ENV JRE_HOME /usr/local/jdk/jdk1.8.0_151/jre
ENV PATH $PATH:$JAVA_HOME/bin:$JRE_HOME/bin
RUN mkdir -p /data/logs
WORKDIR  /data
RUN echo "export LC_ALL=zh_CN.utf8" >> /etc/profile
